#!/bin/bash

if [ -z "$1" ]; then
  echo "usage: $0 source-dir"
  exit 3
fi

mount /trinket
rsync -av -L --exclude "$1/boot_out.txt" \
      --no-owner --no-group --delete --modify-window=2 "$1/" /trinket/
sync
umount /trinket
